name: Deploy RDxClaw to VPS
on:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        
    - name: Build
      run: make generate && make build
      
    - name: Deploy Binary
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "build/rdxclaw-linux-amd64"
        target: "/tmp/rdxclaw"
        
    - name: Restart Service
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo mv /tmp/rdxclaw /usr/local/bin/rdxclaw
          sudo chmod +x /usr/local/bin/rdxclaw
          sudo systemctl restart rdxclaw || sudo systemctl start rdxclaw
          sudo systemctl status rdxclaw --no-pager -l
